apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-playground-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm-playground-backend
  template:
    metadata:
      labels:
        app: llm-playground-backend
    spec:
      containers:
      - name: backend
        image: llm-playground/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: llm-playground-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sandbox-cleanup
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: llm-playground/backend:latest
            command: ["python", "cleanup_old_sandboxes.py"]
          restartPolicy: OnFailure